name: Test coverage

env:
  CARGO_TERM_COLOR: always

on:
  pull_request:

jobs:
  test_coverage:
    name: Run test coverage check
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Generate code coverage
        run: |
          cargo tarpaulin --verbose --workspace --timeout 120 --ignore-tests
